# Generated by Django 4.2.5 on 2025-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("author_name", models.CharField(max_length=100)),
                ("featured_image", models.ImageField(upload_to="blog/")),
                ("content", models.TextField()),
                ("summary", models.TextField()),
                ("date_posted", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
